name: LimitChanger
version: '${project.version}'
main: by.teradapter.limitchanger.LimitChanger
api-version: '1.16'
authors: [TerAdapter]
commands:
  limitchanger:
    aliases:
      - lc
permissions:
  limitchanger.command.main:
    default: op